#!/bin/sh

export DEBUG=true
export HTTP_SERVER_READ_TIMEOUT=20
export HTTP_SERVER_WRITE_TIMEOUT=60
export HTTP_SERVER_IDLE_TIMEOUT=120
export HTTP_SERVER_PORT=:1450

export DATABASE_POSTGRES_HOST=db1.ec2.rmv.dev.br
export DATABASE_POSTGRES_PORT=6432
export DATABASE_POSTGRES_POOL_MAX_LIFETIME_CONNECTION=300
export DATABASE_POSTGRES_NAME=snetdb
export DATABASE_POSTGRES_USER=godinlogistica
export DATABASE_POSTGRES_PASSWORD='zp27N;XaV(M8'
export DATABASE_POSTGRES_LOG=/dev/null 2>&1

go run cmd/app/main.go