#!/bin/sh

export DEBUG=false
export HTTP_SERVER_READ_TIMEOUT=20
export HTTP_SERVER_WRITE_TIMEOUT=60
export HTTP_SERVER_IDLE_TIMEOUT=120
export HTTP_SERVER_PORT=:1450

export DATABASE_POSTGRES_HOST=postgres
export DATABASE_POSTGRES_PORT=6432
export DATABASE_POSTGRES_POOL_MAX_LIFETIME_CONNECTION=300
export DATABASE_POSTGRES_NAME=jampa_trip_db
export DATABASE_POSTGRES_USER=jampa_trip_user
export DATABASE_POSTGRES_PASSWORD=jampa_trip_password
export DATABASE_POSTGRES_LOG=/workspace/logs/database.log

go run cmd/main.go