openapi: 3.0.3

info:
  title: Jampa Trip
  version: 1.0.0
  description: >
    Aplicação mobile com base no TCC do curso de Ciência da Computação.

servers:
  - url: http://127.0.0.1:1450
    description: Servidor da Aplicação

paths:
  /fornecedor/cadastrar:
    $ref: './paths/fornecedor/cadastrar.yaml'

  /fornecedor/login:
    $ref: './paths/fornecedor/login.yaml'

components:
  schemas:
    $ref: './components/schemas.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []