openapi: 3.0.3

info:
  title: Jampa Trip API
  version: 1.0.0
  description: >
    O **Jampa Trip Backend** é uma API REST desenvolvida em Go que serve como backend para uma aplicação mobile de turismo. O projeto foi desenvolvido como parte de um TCC (Trabalho de Conclusão de Curso) do curso de Ciência da Computação, focando na gestão de fornecedores de serviços turísticos e clientes.
servers:
  - url: http://127.0.0.1:1450
    description: Servidor da Aplicação

paths:
  # HEALTH CHECK
  /health-check:
    $ref: './paths/health-check/health-check.yaml'

  # AUTHENTICATION
  /jampa-trip/api/v1/login:
    $ref: './paths/login/login.yaml'
  /jampa-trip/api/v1/refresh:
    $ref: './paths/auth/refresh.yaml'

  # COMPANIES
  /jampa-trip/api/v1/companies:
    $ref: './paths/companies/create_list.yaml'
  /jampa-trip/api/v1/companies/{id}:
    $ref: './paths/companies/get_update.yaml'

  # CLIENTS
  /jampa-trip/api/v1/clients:
    $ref: './paths/clients/create_list.yaml'
  /jampa-trip/api/v1/clients/{id}:
    $ref: './paths/clients/get_update.yaml'

  # CARDS
  /jampa-trip/api/v1/clients/{customer_id}/cards:
    $ref: './paths/cards/cards.yaml'
  /jampa-trip/api/v1/clients/{customer_id}/cards/{card_id}:
    $ref: './paths/cards/card_operations.yaml'

  # PAYMENTS
  /jampa-trip/api/v1/payments/credit-card:
    $ref: './paths/payments/credit_card.yaml'
  /jampa-trip/api/v1/payments/debit-card:
    $ref: './paths/payments/debit_card.yaml'
  /jampa-trip/api/v1/payments/pix:
    $ref: './paths/payments/pix.yaml'
  /jampa-trip/api/v1/payments:
    $ref: './paths/payments/list_payments.yaml'
  /jampa-trip/api/v1/payments/{id}:
    $ref: './paths/payments/payment_operations.yaml'

  # TOURS
  /jampa-trip/api/v1/tours:
    $ref: './paths/tours/tours.yaml'
  /jampa-trip/api/v1/tours/{id}:
    $ref: './paths/tours/tour_operations.yaml'
  /jampa-trip/api/v1/tours/my-tours:
    $ref: './paths/tours/my_tours.yaml'

  # FEEDBACKS
  /jampa-trip/api/v1/feedback:
    $ref: './paths/feedback/feedbacks.yaml'
  /jampa-trip/api/v1/feedback/{id}:
    $ref: './paths/feedback/feedback_operations.yaml'
  /jampa-trip/api/v1/feedback/average-rating:
    $ref: './paths/feedback/average_rating.yaml'
  /jampa-trip/api/v1/feedback/rating-distribution:
    $ref: './paths/feedback/rating_distribution.yaml'
  /jampa-trip/api/v1/feedback/recent:
    $ref: './paths/feedback/recent_feedbacks.yaml'

components:
  schemas:
    PaymentResponse:
      $ref: './components/schemas.yaml#/PaymentResponse'
    PaymentMethodsResponse:
      $ref: './components/schemas.yaml#/PaymentMethodsResponse'
    PaymentMethodInfo:
      $ref: './components/schemas.yaml#/PaymentMethodInfo'
    PaymentMethodSetting:
      $ref: './components/schemas.yaml#/PaymentMethodSetting'
    CardNumberSetting:
      $ref: './components/schemas.yaml#/CardNumberSetting'
    BinSetting:
      $ref: './components/schemas.yaml#/BinSetting'
    SecurityCodeSetting:
      $ref: './components/schemas.yaml#/SecurityCodeSetting'
    FinancialInstitution:
      $ref: './components/schemas.yaml#/FinancialInstitution'
    ErrorResponse:
      $ref: './components/schemas.yaml#/ErrorResponse'
    LoginUnifiedRequest:
      $ref: './components/schemas.yaml#/LoginUnifiedRequest'
    LoginResponse:
      $ref: './components/schemas.yaml#/LoginResponse'
    UserLoginData:
      $ref: './components/schemas.yaml#/UserLoginData'
    CreateClientRequest:
      $ref: './components/schemas.yaml#/CreateClientRequest'
    CreateCompanyRequest:
      $ref: './components/schemas.yaml#/CreateCompanyRequest'
    RefreshTokenRequest:
      $ref: './components/schemas.yaml#/RefreshTokenRequest'
    RefreshTokenResponse:
      $ref: './components/schemas.yaml#/RefreshTokenResponse'
    Company:
      $ref: './components/schemas.yaml#/Company'
    Pagination:
      $ref: './components/schemas.yaml#/Pagination'
    CreateTourRequest:
      $ref: './components/schemas.yaml#/CreateTourRequest'
    UpdateTourRequest:
      $ref: './components/schemas.yaml#/UpdateTourRequest'
    TourResponse:
      $ref: './components/schemas.yaml#/TourResponse'
    CreateTourResponse:
      $ref: './components/schemas.yaml#/CreateTourResponse'
    UpdateTourResponse:
      $ref: './components/schemas.yaml#/UpdateTourResponse'
    ListToursResponse:
      $ref: './components/schemas.yaml#/ListToursResponse'
    MyTourResponse:
      $ref: './components/schemas.yaml#/MyTourResponse'
    GetMyToursResponse:
      $ref: './components/schemas.yaml#/GetMyToursResponse'
    DeleteTourResponse:
      $ref: './components/schemas.yaml#/DeleteTourResponse'
    PaginationResponse:
      $ref: './components/schemas.yaml#/PaginationResponse'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []