openapi: 3.0.3

info:
  title: Jampa Trip
  version: 1.0.0
  description: >
    Aplicação mobile com base no TCC do curso de Ciência da Computação.

servers:
  - url: http://127.0.0.1:1450
    description: Servidor da Aplicação

paths:
  # HEALTH CHECK
  /health-check:
    $ref: './paths/health-check/health-check.yaml'

  # EMPRESA
  /jampa-trip/api/v1/empresas/login:
    $ref: './paths/empresa/login.yaml'
  /jampa-trip/api/v1/empresas/cadastrar:
    $ref: './paths/empresa/cadastrar.yaml'
  /jampa-trip/api/v1/empresas/atualizar/{id}:
    $ref: './paths/empresa/atualizar.yaml'
  /jampa-trip/api/v1/empresas/listar:
    $ref: './paths/empresa/listar.yaml'
  /jampa-trip/api/v1/empresas/obter/{id}:
    $ref: './paths/empresa/obter.yaml'

  # CLIENTE
  /jampa-trip/api/v1/clientes/login:
    $ref: './paths/cliente/login.yaml'
  /jampa-trip/api/v1/clientes/cadastrar:
    $ref: './paths/cliente/cadastrar.yaml'
  /jampa-trip/api/v1/clientes/atualizar/{id}:
    $ref: './paths/cliente/atualizar.yaml'
  /jampa-trip/api/v1/clientes/listar:
    $ref: './paths/cliente/listar.yaml'
  /jampa-trip/api/v1/clientes/obter/{id}:
    $ref: './paths/cliente/obter.yaml'

components:
  schemas:
    $ref: './components/schemas.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []